### ISSUE TITLE
Add Repo URL to Orb Description

### ISSUE THREAD

**Issue by FelicianoTech** [CircleCI-Public/irc-orb#1]
This orb needs the URL of this repository in its top-level description.

**Comment by alicehsiao** [comment]
Can I work on this? Should I just add the link next to this description: "Send custom IRC notifications from CircleCI."?

**Comment by FelicianoTech** [comment]
Yes, it needs to be inside that YAML value for the description. Keep in mind, if you're here for Hacktoberfest, it doesn't start until October 1st.

**Comment by alicehsiao** [comment]
Ah gotcha!

**Comment by KyleTryon** [comment]
Many PRs have been opened for this issue.
