### ISSUE TITLE
Fix CI Badge

### ISSUE THREAD

**Issue by FelicianoTech** [CircleCI-Public/irc-orb#3]
It's using the wrong/old GitHub org name and repo name.

**Comment by vhawk19** [comment]
Is this issue open?

I would love to work on this issue. Where is it using the wrong org name and repo name? I think i saw a different version of the org name and repo name in the description. Is that the issue?

**Comment by FelicianoTech** [comment]
I'm not sure what you mean my "open".

This issue is referring to the CI status that's located near the top of of readme file.

Also, just a heads up that if you're interested in participating in Hacktoberfest, it doesn't start until October 1st.
